### ISSUE TITLE
不会吃小红

### ISSUE THREAD

**Issue by Sh198850** [peko-bot/liver-collection#50]
请问作者还有在用吗?好像系统更新后无法使用了

**Comment by orzyyyy** [comment]
已经弃坑两三年了...如果是前段时间能用，到游戏更新后不能用，那就是吃小红的 api 被改过了，那这个插件就亡了。

**Comment by orzyyyy** [comment]
是之前可以，现在突然不行吗？

**Comment by Sh198850** [comment]
昨天还可以，今天四象开后就不行了

**Comment by orzyyyy** [comment]
那很遗憾，这扩展苟了两三年，今天正式寿终正寝了。

**Comment by Sh198850** [comment]
很感谢作者做出这个扩展，我也用了许久，时候到了，也该让它走了

**Comment by qsyyy** [comment]
今天一直用的填表网崩了，重新找了一个，但是插件不能一键舔婊了。试了一下修改代码，但是看不懂要怎么改。。看来我要从零开始学js了

**Comment by orzyyyy** [comment]
@qsyyy 可以试着改下[这里](https://github.com/peko-bot/liver-collection/blob/master/manifest.json#L13)的地址，不是这几个 url 扩展就没权限。

**Comment by qsyyy** [comment]
@orzyyyy 地址是 r.gbf-tbw.tk 我改了再更新，扩展可以在这个URL运行，但是还是不能跳转
`matches": [
        "*://game.granbluefantasy.jp/*",
        "*://gbf.game.mbga.jp/*",
        "*://gbf-tbw.tk/*",
        "*://tbw.346lab.org/*",
        "*://gbf-raidfinder.aikats.us/*",
		"*://r.gbf-tbw.tk/*"
      ],`

**Comment by qsyyy** [comment]
如果不麻烦的话可以请你看看哪里有问题吗

**Comment by orzyyyy** [comment]
@qsyyy 可以运行和可以跳转是两回事。目前跳转到选召唤页的流程是：
1. 直接进房。通过房间码请求召唤页 url，浏览器 api 直接跳转。
2. 如果是因为豆子不够导致没法进房，那就会先去吃豆子，否则就重试。

可以看看文件名叫 `battleCheck` 的文件，background、contentScript、inject 下都有。

**Comment by orzyyyy** [comment]
我只能猜一下问题在哪，我没测试的号。

**Comment by qsyyy** [comment]
请求的地址没有变，还是`quest/battle_key_check`。
只有我添加的新网址不能跳转，原来的`gbf-raidfinder.aikats.us/`还是可以的。
我想可能是这个 `r.gbf-tbw.tk`跟别的填表网有什么不一样的地方？

**Comment by orzyyyy** [comment]
那就是[这里](https://github.com/peko-bot/liver-collection/blob/master/background/battleCheck.js#L31)的问题了。本质上扩展是监听自剪贴板的，只要剪贴板有变化，那就执行跳转。

**Comment by qsyyy** [comment]
要检查这里有没有问题我得去看一下文档，不然根本看不懂啊

**Comment by qsyyy** [comment]
在浏览器调试时我要怎么找到battleCheck.js 这部分代码啊？

**Comment by orzyyyy** [comment]
f12 -> ctrl + p -> 输入 battle
